### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [aliakseis/LIII#1]
Currently (as of version [0.1.0.1](https://github.com/aliakseis/LIII/releases/tag/0.1.0.1)) [LIII BitTorrent Client](https://github.com/aliakseis/LIII) saves data and settings in AppData:

`C:\Users\User\AppData\Local\LIII\LIII`

I would like to suggest portable mode- data and settings saved not in AppData but in program folder (where is the executable- **LIII.exe**). This can be implemented in a variety of ways, several examples:

1. **command-line argument** - if **LIII BitTorrent Client** is started with a specific parameter, for example `LIII.exe -portable`, data and settings are saved in program folder;
2. **portable flag** - specific file in program folder (for example `portable` without extension or `portable.txt`) triggers portable mode, when **LIII BitTorrent Client** starts it checks program folder for such file and if it is there data and settings are saved in program folder;
3. **configuration file** - when **LIII BitTorrent Client** starts it checks program folder for the configuration file (`modelState.xml`) and if it is there the program uses it and also saves torrents data in program folder;
4. **specific sub-folder** - when **LIII BitTorrent Client** starts it checks the program folder for a specific sub-folder (for example `LIII` or `data`) and of it is there it saves data and settings in this sub-folder;
5. **executable name** - if the executable is renamed from `LIII.exe` to `LIII-Portable.exe` the program starts in portable mode, data and settings are saved in program folder;
6. **option in settings** - new check box- `Portable mode`, which, if selected, forces the program to save data and settings in program folder;
7. **portable installation** - when the program is installed beside normal installation it offers also portable installation, which just extracts the files to a folder specified by the user and data and settings are saved in program folder;
8. **portable version** - separate portable version- the program is packed in archive, the user extracts the archive and runs the executable, data and settings are saved in program folder;

Any of these methods would be fine for me, however I prefer method **2** (**portable flag**)- it is easy for the user, there is no need to use command-line parameters, creating `portable` file in program folder enables portable mode, deleting it disables portable mode- easy, convenient, simple, flexible.

I believe that portable mode would be useful not only for me- there are users who prefer portable programs which do not write outside their folders (no AppData, no User profile, no Windows registry). Such programs are easy to backup and transfer.

In fact many torrent clients ([Deluge](https://deluge-torrent.org/), [Halite](http://www.binarynotions.com/halite-bittorrent-client/), [PicoTorrent](https://picotorrent.org/), [qBittorrent](https://www.qbittorrent.org/), [Tixati](https://www.tixati.com/), [uTorrent](https://www.utorrent.com/), etc) already support portable mode.

If portable mode is implemented in future releases of **LIII BitTorrent Client** I may write a short review about the program in a forum dedicated to portable freeware.

**Comment by aliakseis** [comment]
Thank you! Sounds like a good suggestion. I'm on it.

**Comment by aliakseis** [comment]
Just rolled a new update according to option #2 (just portable without extension, directory works too).

**Comment by smaragdus** [comment]
@aliakseis 

> Just rolled a new update according to option #2 (just portable without extension, directory works too).

Excellent news! I will download and test it soon. I may also suggest a few other enhancements.

Regards

**Comment by smaragdus** [comment]
@aliakseis 

I did a very brief testing of **LIII BitTorrent Client** version [0.1.0.2](https://github.com/aliakseis/LIII/releases/tag/0.1.0.2) and I can confirm that creating `portable` file in program folder really triggers portable mode- data and settings saved in `LIII` sub-folder. This is what I needed, thank you.

By the way you wrote that "directory works too"- what do you mean exactly? That creating `LIII` sub-folder should also trigger portable mode? In my test it did not.

Anyway, the program has good potential and I will do more tests. I will also write a short article about the program as I promised (I hope I will do it soon).

Since portable mode is implemented you may close this issue.

**Comment by aliakseis** [comment]
I mean that installation script modification was easier for the directory:  https://github.com/aliakseis/LIII/blob/7df6792644e45d174c37dcaab2b176e943660685/setup.iss#L35
But I am afraid that adding this option to the installation is not quite good because enabling it can break installation to the default directory.

**Comment by smaragdus** [comment]
@aliakseis 

I posted a short review about the program at The Portable Freeware Forum, you can find it [here](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24360).

I presumed that it should work under Windows 7 or newer, is that right?

**Comment by aliakseis** [comment]
Thank you!
Yes, it must be right. Unfortunately don't have a Windows 7 at hand. Probably I'll try it on a VM when I have time.
Theoretically it can be built for XP as well: https://stackoverflow.com/a/50258630
