### ISSUE TITLE
[Request] Show total speed of all torrents

### ISSUE THREAD

**Issue by ArcticGems** [aliakseis/LIII#10]
It would be very nice if you could show total speed of all torrents, for example (or something similar) =

[DHT: 389 nodes][Total DL|UL: 3.49MB/s | 1.73MB/s]

**Comment by aliakseis** [comment]
Now that there are more than one parameter to display, probably it makes sense to use a statusbar, right?

**Comment by aliakseis** [comment]
Seems to be OK now...
