### ISSUE TITLE
Docs needed

### ISSUE THREAD

**Issue by JeremyWu917** [aliakseis/LIII#14]
This project will be more popular if there is more details about it in readme.md 👍

**Comment by ArcticGems** [comment]
Great! You have updated the the readme.md. 👍 

Maybe you should also add that you use a custom build of libtorrent?? 😃

**Comment by ArcticGems** [comment]
@JeremyWu917 

Maybe you can close this issue now?

**Comment by JeremyWu917** [comment]
@ArcticGems 
Sorry for the late response 😢 
BTW,  good job! 👍
