### ISSUE TITLE
versionconf

### ISSUE THREAD

**Issue by Tellie** [aliakseis/LIII#5]
Hello,
tried to port it to OS/2 using qmake v5.13.1 and cmake v3.10.3
When i run cmake i get:
-- Found Threads: TRUE
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   chrono
--   random
--   atomic
--   date_time
CMake Error at src/CMakeLists.txt:451 (VersionConf):
  VersionConf Macro invoked with incorrect arguments for macro named:
  VersionConf

-- Configuring incomplete, errors occurred!
See also "F:/git/torrent/os2/CMakeFiles/CMakeOutput.log".
See also "F:/git/torrent/os2/CMakeFiles/CMakeError.log".

Any thoughts about this??

**Comment by aliakseis** [comment]
Hello,
It looks like the problem is caused by the missing OS/2 section here:
https://github.com/aliakseis/LIII/blob/7e54629b79f9d0f5bf3b7db61e88c5774f17ebff/CMakeLists.txt#L232
Not sure what should be set there.  Unfortunately I am not familiar with building of executables for OS/2...

**Comment by Tellie** [comment]
hi
thankz i fix that, but now i get next error...

F:/git/torrent/src/gui/preferences.cpp:252:41: error: reference to 'Tr' is ambiguous
             QMessageBox::critical(this, Tr::Tr(PROJECT_FULLNAME_TRANSLATION), tr("Enter a valid proxy address."));
                                         ^
F:/git/torrent/src/gui/preferences.cpp:32:29: note: candidates are: namespace Tr = utilities::utilities::Tr;
 namespace Tr = utilities::Tr;
                             ^
In file included from F:/git/torrent/src/gui/preferences.cpp:30:0:
F:/git/torrent/src/main/globals.h:31:29: note:                 namespace <unnamed>::Tr = utilities::utilities::Tr;
 namespace Tr = utilities::Tr;
                             ^
F:/git/torrent/src/gui/preferences.cpp:261:41: error: reference to 'Tr' is ambiguous
             QMessageBox::critical(this, Tr::Tr(PROJECT_FULLNAME_TRANSLATION), tr("Enter a valid proxy port."));
                                         ^
F:/git/torrent/src/gui/preferences.cpp:32:29: note: candidates are: namespace Tr = utilities::utilities::Tr;
 namespace Tr = utilities::Tr;
                             ^
In file included from F:/git/torrent/src/gui/preferences.cpp:30:0:
F:/git/torrent/src/main/globals.h:31:29: note:                 namespace <unnamed>::Tr = utilities::utilities::Tr;
 namespace Tr = utilities::Tr;

any idea :)

**Comment by aliakseis** [comment]
I hope this fixes your latest issue:
https://github.com/aliakseis/LIII/commit/801e7efd929714a160341b338f1fa59f454cd94b

**Comment by Tellie** [comment]
Hello,
Yah thankz that worked like a charme :)
Now i think the last error i get:

[100%] Linking CXX executable LIII.exe
c++.exe: error: /VERSION:0.1: No such file or directory
make[2]: *** [src/LIII.exe] Error 1
make[1]: *** [src/CMakeFiles/LIII.dir/all] Error 2
make: *** [all] Error 2

**Comment by aliakseis** [comment]
Hello,
I only see a suspicious line here:
https://github.com/aliakseis/LIII/blob/801e7efd929714a160341b338f1fa59f454cd94b/src/CMakeLists.txt#L457
Probably it was used as a sample for the OS/2 build...

**Comment by Tellie** [comment]
Hello,

Should I disable that line or what do you exactly what I should try ?

Op zo 24 nov. 2019 19:49 schreef aliakseis <notifications@github.com>:

**Comment by Tellie** [comment]
Hello,

Ok i found the cullpit for /VERSION

But now i get:
Scanning dependencies of target LIII
[100%] Building CXX object src/CMakeFiles/LIII.dir/main/main.cpp.o
[100%] Building CXX object src/CMakeFiles/LIII.dir/qrc_resources-LIII.cpp.o
[100%] Linking CXX executable LIII.exe
emxomf warning: Input file '3rdparty/torrent-rasterbar/torrent-rasterbar.a(session_impl.cpp.o)' has more HLL debug types than we can index in PUBDEF and EXTDEF records.
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities18isDefaultMagnetAppEv'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities11MoveToTrashERK7QString'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(downloadcollectiontreeview.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities19setDefaultMagnetAppEj'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities21unsetDefaultMagnetAppEj'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities20setDefaultTorrentAppEj'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities22unsetDefaultTorrentAppEj'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj)
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities19isDefaultTorrentAppEv'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj)
    D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj)
Ignoring unresolved externals reported from weak prelinker.
Error! E2028: __ZN9utilities20setDefaultTorrentAppEj is an undefined reference
Error! E2028: __ZN9utilities22unsetDefaultTorrentAppEj is an undefined reference
Error! E2028: __ZN9utilities19setDefaultMagnetAppEj is an undefined reference
Error! E2028: __ZN9utilities21unsetDefaultMagnetAppEj is an undefined reference
Error! E2028: __ZN9utilities19isDefaultTorrentAppEv is an undefined reference
Error! E2028: __ZN9utilities18isDefaultMagnetAppEv is an undefined reference
Error! E2028: __ZN9utilities11MoveToTrashERK7QString is an undefined reference
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj): undefined symbol __ZN9utilities20setDefaultTorrentAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj): undefined symbol __ZN9utilities22unsetDefaultTorrentAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj): undefined symbol __ZN9utilities19setDefaultMagnetAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(application.cpp.obj): undefined symbol __ZN9utilities21unsetDefaultMagnetAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj): undefined symbol __ZN9utilities19isDefaultTorrentAppEv
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj): undefined symbol __ZN9utilities18isDefaultMagnetAppEv
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj): undefined symbol __ZN9utilities20setDefaultTorrentAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(mainwindow.cpp.obj): undefined symbol __ZN9utilities19setDefaultMagnetAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities19isDefaultTorrentAppEv
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities18isDefaultMagnetAppEv
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities20setDefaultTorrentAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities19setDefaultMagnetAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities21unsetDefaultMagnetAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(preferences.cpp.obj): undefined symbol __ZN9utilities22unsetDefaultTorrentAppEj
file D:\Temp\ldconv_LIII_LIB_a_86c5ddadfb5179180.lib(downloadcollectiontreeview.cpp.obj): undefined symbol __ZN9utilities11MoveToTrashERK7QString
make[2]: *** [src/LIII.exe] Error 1
make[1]: *** [src/CMakeFiles/LIII.dir/all] Error 2
make: *** [all] Error 2

**Comment by aliakseis** [comment]
I see, that's because there is system dependent associate_app_linux.cpp, associate_app_mac.cpp, associate_app_win.cpp. It is set up here:
https://github.com/aliakseis/LIII/blob/801e7efd929714a160341b338f1fa59f454cd94b/src/common/utilities/CMakeLists.txt#L64
This functionality is in no way critical, and empty associate_app_linux.cpp implementation can be used as a template.

**Comment by Tellie** [comment]
Hello,
Yes this fixed it :)
But i still get this error:
[ 98%] Linking CXX executable LIII.exe
emxomf warning: Input file '3rdparty/torrent-rasterbar/torrent-rasterbar.a(session_impl.cpp.o)' has more HLL debug types than we can index in PUBDEF and EXTDEF records.
weakld: error: Unresolved symbol (UNDEF) '__ZN9utilities11MoveToTrashERK7QString'.
weakld: info: The symbol is referenced by:
    D:\Temp\ldconv_LIII_LIB_a_da5ddbfcf0147c70.lib(downloadcollectiontreeview.cpp.obj)
Ignoring unresolved externals reported from weak prelinker.
Error! E2028: __ZN9utilities11MoveToTrashERK7QString is an undefined reference
file D:\Temp\ldconv_LIII_LIB_a_da5ddbfcf0147c70.lib(downloadcollectiontreeview.cpp.obj): undefined symbol __ZN9utilities11MoveToTrashERK7QString
make[2]: *** [src/LIII.exe] Error 1
make[1]: *** [src/CMakeFiles/LIII.dir/all] Error 2
make: *** [all] Error 2

**Comment by aliakseis** [comment]
Hello,

I hope this fixes the latest issue:
https://github.com/aliakseis/LIII/commit/9fc657a1fdeb6406ae102057f92a9355b646c3d8#diff-cb11ec72b7d11f56c544abffbab6b524

**Comment by Tellie** [comment]
Hello,
Yes, this corrected the latest error..
But now a new problem showed up ;(
After starting i get:
[F:\git\torrent\os22\src]lIII
qt.qpa.plugin: Could not find the Qt platform plugin "os2" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
I ported plenty other programs, and this is first time i see this error...

**Comment by aliakseis** [comment]
Can it be a similar issue?
https://forum.qt.io/topic/90293/could-not-find-or-load-the-qt-platform-plugin-windows-in

**Comment by aliakseis** [comment]
A couple of places where OS/2 case handling may help:
https://github.com/aliakseis/LIII/blob/9fc657a1fdeb6406ae102057f92a9355b646c3d8/cmake/integrate-qt.cmake#L180
https://github.com/aliakseis/LIII/blob/9fc657a1fdeb6406ae102057f92a9355b646c3d8/cmake/integrate-qt.cmake#L255

**Comment by Tellie** [comment]
Hello,
If added to line 179 if(WIN32 OR OS2) and line 224  if(WIN32 OR APPLE OR OS2)

But now i get:
CMake Error at cmake/integrate-qt.cmake:175 (message):
  cannot add post_build step to /@unixroot/usr/plugins/imageformats/qico.dll
Call Stack (most recent call first):
  cmake/integrate-qt.cmake:247 (QT_ADD_POSTBUILD_STEP)
  cmake/integrate-qt.cmake:335 (INSTALL_IMAGEFORMATS)
  src/CMakeLists.txt:532 (INSTALL_QT_PLUGINS)

**Comment by Tellie** [comment]
Btw on os2 the plugings are in :
C:\usr\lib\qt5\plugins\imageformats

**Comment by aliakseis** [comment]
It is strange, where did this @unixroot come from...
Still I suppose that the os2 plugin belongs to the platforms folder, not the imageformats one.
I believe that it still can run if we manually copy both platforms and imageformats folders next to the executable.

**Comment by Tellie** [comment]
Ok,
Unixroot is set in config.sys like SET UNIXROOT=C:
https://i.imgur.com/2WaCg3G.png
https://i.imgur.com/NLyxU7L.png

It also searched the translation so i set in translatable line 17 also to os2

Does it looks like the other OSses ?
Thankz 1000x for all the help :)))))

**Comment by aliakseis** [comment]
It seems so. But it shouldn't be critical with translation. In the worst case you'll get only default English version.
