### ISSUE TITLE
[Request] Show somewhere how much DHT nodes LIII is connected too

### ISSUE THREAD

**Issue by ArcticGems** [aliakseis/LIII#8]
Show somewhere how much DHT nodes LIII is connected too, maybe add "[DHT: xxx nodes]" in the program title bar (for example: LIII Bittorrent Client [DHT: 389 nodes]). Somewhere else is okey as well.

With this you can see if you have some type of connectivity issue.

**Comment by aliakseis** [comment]
Thank you for the suggestion!

Seems to be OK now.
